ShopStrumentiMusicali/Controllers/AdministrationController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShopStrumentiMusicali.Database;
using ShopStrumentiMusicali.Models;
using System.Data;

namespace ShopStrumentiMusicali.Controllers {
    public class AdministrationController : Controller {
        public IActionResult IndexAdm() {
            
            using (ParamusicContext db = new ParamusicContext()) {
                List<Instrument> instrumentsList = db.Instruments.ToList<Instrument>();
                return View("IndexAdm", instrumentsList);
            }
   
        }
        [Authorize(Roles = "Admin")]
        public IActionResult Warehouse() {

            using (ParamusicContext db = new ParamusicContext()) {
                List<Instrument> instrumentsList = db.Instruments.OrderBy(ins => ins.Quantity).ToList<Instrument>();
                foreach(Instrument ins in instrumentsList)
                {
                    if(ins.Quantity <= 10)
                    {
                        ins.State = "Da ordinare";
                    }
                    if (ins.Quantity == 0)
                    {
                        ins.State = "Esaurito";
                    }
                    if (ins.Quantity > 10)
                    {
                        ins.State = "Disponibile";
                    }
                    
                }
                
                db.SaveChanges();
                return View("Warehouse", instrumentsList);
            }

        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Create() {
            using (ParamusicContext db = new ParamusicContext())
            {
                List<Category> categoriesFromDb = db.Categories.ToList<Category>();
                List<ShopTransaction> shopTransactionsFromDb = db.ShopTransactions.ToList<ShopTransaction>();

                InstrumentCategoriesView modelForView = new InstrumentCategoriesView();
                modelForView.Instrument = new Instrument();

                //List<Category> selectList = CategoriesToSelectList(categoriesFromDb);

                modelForView.Categories = categoriesFromDb;
              //  modelForView.ShopTransactions = shopTransactionsFromDb;
                return View("Create", modelForView);
            }
        }

        /*private static List<Category> CategoriesToSelectList(List<Category> categoriesFromDb)
        {
            List<Category> selectList = new List<Category>();
            foreach (Category category in categoriesFromDb)
            {
                Category item = new Category();
                item = category;
                selectList.Add(item);
            }

            return selectList;
        }*/

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult Create(InstrumentCategoriesView formData) {

            if (!ModelState.IsValid) {
                Console.WriteLine("Debug here");

                using (ParamusicContext db = new ParamusicContext()) {
                    List<Category> categoriesFromDb = db.Categories.ToList<Category>();
					
					

					formData.Categories = categoriesFromDb;
                    
                }


                return View("Create", formData);
            }

            using (ParamusicContext db = new ParamusicContext()) {
                db.Instruments.Add(formData.Instrument);
                db.SaveChanges();
            }

            return RedirectToAction("IndexAdm");
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Update(int id) {
            using (ParamusicContext db = new ParamusicContext()) {
                Instrument instrumentToUpdate = db.Instruments.Where(instrument => instrument.Id == id).FirstOrDefault();

                if (instrumentToUpdate == null) {
                    return NotFound("Lo strumento non è stato trovato");
                }

                List<Category> categoriesFromDb = db.Categories.ToList<Category>();

                InstrumentCategoriesView modelForView = new InstrumentCategoriesView();

                //List<Category> selectList = CategoriesToSelectList(categoriesFromDb);

                modelForView.Instrument = instrumentToUpdate;
                modelForView.Categories = categoriesFromDb;

                return View("Update", modelForView);
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult Update(int id, InstrumentCategoriesView formData)
        {
            if (!ModelState.IsValid)
            {

                using (ParamusicContext db = new ParamusicContext())
                {
                    List<Category> categoriesFromDb = db.Categories.ToList<Category>();
                    //List<Category> selectList = CategoriesToSelectList(categoriesFromDb);

                    formData.Categories = categoriesFromDb;
                }

                return View("Update", formData);
            }

            using (ParamusicContext db = new ParamusicContext())
            {

                Instrument instrumentToUpdate = db.Instruments.Where(instrument => instrument.Id == id).FirstOrDefault();

                if (instrumentToUpdate != null)
                {
                    instrumentToUpdate.Name = formData.Instrument.Name;
                    instrumentToUpdate.Description = formData.Instrument.Description;
                    instrumentToUpdate.ImageURL = formData.Instrument.ImageURL;
                    instrumentToUpdate.CategoryID = formData.Instrument.CategoryID;
                    instrumentToUpdate.Quantity = formData.Instrument.Quantity;
                    instrumentToUpdate.Price = formData.Instrument.Price;

                    db.SaveChanges();

                    return RedirectToAction("IndexAdm");
                }
                else
                {
                    return NotFound("Lo strumento che volevi modificare non è stato trovato!");
                }
            }
        }

        [HttpGet]
        [Authorize(Roles = "Cliente")]
        public IActionResult Purchase(int id)
        {
            using (ParamusicContext db = new ParamusicContext())
            {
                Instrument instrumentToUpdate = db.Instruments.Where(instrument => instrument.Id == id).FirstOrDefault();

                if (instrumentToUpdate == null)
                {
                    return NotFound("Lo strumento non è stato trovato");
                }

                List<Category> categoriesFromDb = db.Categories.ToList<Category>();

                InstrumentCategoriesView formData = new InstrumentCategoriesView();


                formData.Instrument = instrumentToUpdate;
                formData.Categories = categoriesFromDb; // non mi serve

                return View("Purchase", formData);
            }

        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Cliente")]
        public IActionResult Purchase(int id, InstrumentCategoriesView formData) {
            if (!ModelState.IsValid) {

                using (ParamusicContext db = new ParamusicContext()) {
                    List<Category> categoriesFromDb = db.Categories.ToList<Category>();
                    //List<Category> selectList = CategoriesToSelectList(categoriesFromDb);

                    formData.Categories = categoriesFromDb;
                }

                return View("Purchase", formData);
            }

            
            

            using (ParamusicContext db = new ParamusicContext()) {
                
                Instrument instrumentToUpdate = db.Instruments.Where(instrument => instrument.Id == id).FirstOrDefault();
                int qtsub = (int)instrumentToUpdate.Quantity;




                UserTransaction userTransaction = new();

                if (instrumentToUpdate != null) {
					instrumentToUpdate.Quantity = qtsub - formData.Quantity;
                    userTransaction.InstrumentID = (int)instrumentToUpdate.Id;
					userTransaction.TransactionDate = DateTime.Now;
                    userTransaction.TransactionQuantity = formData.Quantity;
                    
                    
                    
                   
                    db.UserTransactions.Add(userTransaction);
                    db.SaveChanges();

                    return RedirectToAction("Index","Home");
                } else {
                    return NotFound("Lo strumento che volevi modificare non è stato trovato!");
                }
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int id) {
            using (ParamusicContext db = new ParamusicContext()) {
                Instrument instrumentToDelete = db.Instruments.Where(instrument => instrument.Id == id).FirstOrDefault();

                if (instrumentToDelete != null) {
                    db.Instruments.Remove(instrumentToDelete);
                    db.SaveChanges();

                    return RedirectToAction("IndexAdm");
                } else {
                    return NotFound("Lo strumento da eliminare non è stato trovato!");
                }
            }
        }




		[HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Resupply(int id)
		{
			using (ParamusicContext db = new ParamusicContext())
			{
				Instrument instrumentToUpdate = db.Instruments.Where(instrument => instrument.Id == id).FirstOrDefault();

				if (instrumentToUpdate == null)
				{
					return NotFound("Lo strumento non è stato trovato");
				}

				List<Category> categoriesFromDb = db.Categories.ToList<Category>();

				InstrumentCategoriesView formData = new InstrumentCategoriesView();


				formData.Instrument = instrumentToUpdate;

ShopStrumentiMusicali/Controllers/RolesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Hosting;
using ShopStrumentiMusicali.Database;

namespace ShopStrumentiMusicali.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RolesController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        public RolesController(RoleManager<IdentityRole> roleManager)
        {
            this._roleManager = roleManager;
        }
        //Lista tuti account creati dal utenti
        public IActionResult Index()
        {
            using (ParamusicContext db = new ParamusicContext())
            {
                List<IdentityRole> ListaRoles = db.Roles.ToList<IdentityRole>();
                return View("Index", ListaRoles);
            }
            
        }

        [HttpGet]
        public IActionResult Create() 
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(IdentityRole model) 
        {
            if(!_roleManager.RoleExistsAsync(model.Name).GetAwaiter().GetResult())
            {
                _roleManager.CreateAsync(new IdentityRole(model.Name)).GetAwaiter().GetResult();    
            }
            return RedirectToAction("Index");
        }

    }
}

ShopStrumentiMusicali/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShopStrumentiMusicali.Database;
using ShopStrumentiMusicali.Models;
using ShopStrumentiMusicali.Repositories;
using System.Data;

namespace ShopStrumentiMusicali.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UserController : Controller
    {
        
        public readonly IUnitofWork _unitofWork;
        private readonly SignInManager<IdentityUser> _signInManager;

        public UserController(IUnitofWork unitofWork , SignInManager<IdentityUser> signInManager) {
            _unitofWork = unitofWork;
            _signInManager = signInManager;
        }
        public IActionResult Index()
        {
           /* using (ParamusicContext db = new ParamusicContext())
            {
                List<IdentityUser> ListaRoles = db.Users.ToList();
                return View("Index", ListaRoles);
            }*/
           
           var users = _unitofWork.User.GetUsers();
            return View(users);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(string id) {
            var user = _unitofWork.User.GetUser(id);
           var roles = _unitofWork.Role.GetRoles();
            var userroles = await _signInManager.UserManager.GetRolesAsync(user);


            var roleitems = roles.Select(role => 
            new SelectListItem(role.Name,role.Id,
            userroles.Any(ur =>ur.Contains(role.Name)))).ToList();

            var vm = new UserRoleModel
            {
                User = user,
               Roles = roleitems,
            };

            return View(vm);
        }
        [HttpPost]
        public async Task<IActionResult> OnPostAsync(UserRoleModel data)
        {
            var user = _unitofWork.User.GetUser(data.User.Id);
            if (user == null)
            {
                return NotFound();
            }

            var userRolesInDb = await _signInManager.UserManager.GetRolesAsync(user);

            //Cicla in UserRoleModel
            //Verifica se Ruolo e assegnato in DB
            //Se assegnato niente
            //Se no assegna ruolo

            var rolesToAdd = new List<string>();
            var rolesToDelete = new List<string>();

            foreach (var role in data.Roles)
            {
                var assignedInDb = userRolesInDb.FirstOrDefault(ur => ur == role.Text);
                if (role.Selected)
                {
                    if (assignedInDb == null)
                    {
                        rolesToAdd.Add(role.Text);
                    }
                }
                else
                {
                    if (assignedInDb != null)
                    {
                        rolesToDelete.Add(role.Text);
                    }
                }
            }

            if (rolesToAdd.Any())
            {
                await _signInManager.UserManager.AddToRolesAsync(user, rolesToAdd);
            }

            if (rolesToDelete.Any())
            {
                await _signInManager.UserManager.RemoveFromRolesAsync(user, rolesToDelete);
            }

            if (data.User.Email != null & data.User.Email != "")
            {
                user.Email = data.User.Email;
            }
            _unitofWork.User.UpdateUser(user);

            return RedirectToAction("Edit", new { id = user.Id });
        }
    }
}
    

ShopStrumentiMusicali/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css">
    <title>ParaMusic Instrument Store</title>
    <style>
        body {
            background-image: url('https://www.wallpapersdsc.net/wp-content/uploads/2017/10/Black-Music-HD-Background.jpg');
        }
    </style>
</head>
<body class="pb-0 mb-0">

<!--SEZIONE HEADER-->
<header>
    <!--Navbar section-->
        <nav class="navbar navbar-expand-lg bg-light">
            <div class="container-fluid">
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar">
                <img class="d-inline-block" src="https://cdn-icons-png.flaticon.com/512/1059/1059909.png?" alt="Logo" width="50" height="50">
                </a>
                <a class="navbar-brand" href="#">Music Instrument Store</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="\Home\Index\">Home</a>
                        </li>
                        @if (!User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" href="\Home\Index\#shop">Chi siamo</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link" href="\Home\Index\#catalog">Catalogo</a>
                        </li>
                        @if (!User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" href="\Home\Index\#contact">Contatti</a>
                            </li>
                        }

                            <!--Bottoni login Registrati-->
                            @if (SignInManager.IsSignedIn(User))
                            {
                            <li class="nav-item">
                                <div class="nav-items">
                                    <a id="manage" class="nav-link text-black" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Ciao: @UserManager.GetUserName(User)!</a>

                                    <form id="logoutForm" class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                                        <button id="logout" type="submit" class="nav-link btn btn-link text-black">Logout</button>
                                    </form>
                                </div>
                             </li>
                            }
                            else
                            {
                            <li class="nav-item">
                                <a class="btn btn-success ms-5" id="login" asp-area="Identity" asp-page="/Account/Login">Login</a>
                                <a class="btn btn-warning ms-4" id="register" asp-area="Identity" asp-page="/Account/Register">Registrati</a>
                            </li>
                            }

                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link btn btn-primary btn-danger"
                               href="@Url.Action("IndexAdm", "Administration")">
                                    Admin
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link  btn btn-primary btn-outline-info text-white" asp-area="" asp-controller="Roles" asp-action="Index">Ruoli</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link  btn btn-primary btn-outline-warning text-white" asp-area="" asp-controller="User" asp-action="Index">Utenti</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link  btn btn-primary btn-outline-success text-white" asp-area="" asp-controller="Administration" asp-action="Warehouse">Magazzino</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link  btn btn-primary btn-outline-success text-white" asp-area="" asp-controller="UserTransactions" asp-action="Index">Transazioni</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>

    </header>

  <!--SEZIONE MAIN-->   
    <div class="container">
    <main role="main" "class="pb-3 mb-0">
        @RenderBody() 
    </main>
    </div>


     <!--Layout footer-->
 @if (!User.IsInRole("Admin")) {
        <section id="contact"></section>
    <footer>
        <div class="container-fluid bg-dark footer">
                 <div class="text-center fs-6 text-white fw-light">

                <p class="text-center fs-4 text-white fw-bolder">Music Instrument Store</p>
                Via 3 Settembre, 17 - 47891 Milano (MN) <br>
                Tel. +39 0549/909670 - Fax +39 0549/909685 <br>
                E-mail: info@ParaMusic.sm <br>
                C.O.E. SM 07256 <br>
                Iscritto al Registro e-commerce al nr. 9999999 del 15/04/2014 <br>
                <a class="nav-link" aria-current="page" href="\Home\Index\">Torna su</a>
            </div>
            
        </div>
    </footer>
    }

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <!--AXIOS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.20.0/axios.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>